language: C
script: ./autogen.sh && ./configure --enable-debug --enable-x11 --enable-realtime --without-system-libtorrent --without-system-ffmpeg --disable-shared && make

before_install:
- sudo apt-get update -qq
- sudo apt-get install libboost1.55-all-dev libboost1.55-tools-dev
- sudo apt-get install libcairo2-dev libpango1.0-dev libasound2-dev libsqlite3-dev libmagic-dev libx11-dev libwebsockets3
- sudo apt-get install yasm
